[[pages]]
path = "main.py"
name = "Tech Challenge 3"
icon = ":house:"
is_section = false

[[pages]]
path = "pages/intro.py"
name = "Introdução"
icon = ":books:"
is_section = false

[[pages]]
path = "pages/analise.py"
name = "Explorações, descobertas e análises"
icon = ":memo:"
is_section = false

[[pages]]
path = "pages/conclusao.py"
name = "Conclusão"
icon = ":sparkles:"
is_section = false

[[pages]]
path = "pages/refs.py"
name = "Referências"
icon = ":globe_with_meridians:"
is_section = false